### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by Epikos1994** [playcanvas/playcanvas-ar#7] opened 2018-02-15 08:18 UTC
Currently having an issue getting the camera to work on Android devices. The play canvas app launches and then just shows a grey/blue screen. This is also reproducible in the demo example you provided.

I tried adding a UI to see if the app wasn't launching at all but I could see it. So it looks like an issue with init/rendering the camera from the device?

I'll test IOS when I get the chance.

I tried looking around in the source to see if I could identify the problem, but no luck.
Just moved to PlayCanvas from Unity, Loving working with AR so far. Fun and easy to play around with.

Any help would be appreciated.
Thanks.

**Comment by willeastcott** [comment] 2018-02-20 06:43
Seems to work fine here on a Huawei Honor:

![img_0178](https://user-images.githubusercontent.com/697563/36410490-1fda969a-15c6-11e8-98c0-dc5c23db8d45.jpg)

What device(s) and browser(s) are you having problems with?

**Comment by Epikos1994** [comment] 2018-02-20 12:04
Tested with a Samsung J5 and a Samsung Note 4.

Mainly testing with the Note 4. Android v6.0.1

Playcanvas shows, loads, completes and then this screen.

![screenshot_2018-02-20-12-59-35-resize](https://user-images.githubusercontent.com/5662206/36423256-781f17b2-163f-11e8-979b-82df464d3f29.png)

**Comment by willeastcott** [comment] 2018-02-20 14:55
And you never see the dialog asking for permission to use the camera?
What do you see if you go to http://get.webgl.org?
Can you remote debug the problem device(s) and get the JavaScript console output?

**Comment by Epikos1994** [comment] 2018-02-20 15:58
Nope, No Dialog asking about the camera.

![image](https://user-images.githubusercontent.com/5662206/36434360-27e19322-165f-11e8-8bcd-bc892f48d5e8.png)

I can, however, dont have access to pc atm. I'll take a look when so.

**Comment by willeastcott** [comment] 2018-02-20 16:07
Wait. There’s no lock on your browser when viewing the app. Does that mean you’re not viewing the link over https? Https is required for camera access.

**Comment by Epikos1994** [comment] 2018-02-20 18:00
Ive just checked. Still the same issue. I tried incognito also to see if there were possible cache settings or something. But the only permissions the page says it has/needed are for sound.

Also reset page settings and data. No luck.

Ill send a screenshot when I get to a pc.

**Comment by cognitiveplus** [comment] 2018-02-20 20:59
I have the same issue on Xiaomi Redmi 3, Android 5.1.1.
Although I get camera dialog on the first try, after confirming it the screen is grey. On subsequent tries there is no camera dialog, only grey screen.

Will try to clone this project, build my custom version and debug it.

**Comment by willeastcott** [comment] 2018-02-21 01:00
But that screen still shows a URL being loaded on http, no? With https you see the https:// and a lock icon to the left of the URL.

**Comment by willeastcott** [comment] 2018-02-21 01:01
OK, let me know what you find out. 😄

**Comment by cognitiveplus** [comment] 2018-02-25 19:38
Ok, here are some findings:
+ Camera entity is working, I can easily see entities attached to it. (#00000000 clear color just results into dark grey background, probably because it makes canvas absolutely transparent, and dark grey remains from preloader div)
+ But video rendering seems to be broken. Playing with script attributes did nothing, so gonna try to debug video rendering itself!

It also may be the issue with getting input from device camera, since placing AR marker in front of it doesn't fire up the cube - so seems like the script doesn't see camera input and can't process it

**Comment by Epikos1994** [comment] 2018-02-25 19:56
Sorry haven't been active. On holiday atm. I'll be back on Thursday to help out.

Gl

**Comment by cognitiveplus** [comment] 2018-02-26 09:34
Another finding - removing calibration .dat file from ArCamera script attribute seems to break desktop version in the same way as it's currently broken on my android - i.e. it just loads to dark grey and doesn't do anything. May be there is an issue with camera calibration file on some androids?

**Comment by cognitiveplus** [comment] 2018-02-26 09:42
I've found the culprit:
ArCamera.prototype.enterAr ::
navigator.mediaDevices.getUserMedia(constraints).then(function (stream) {...}) - the code flow doesn't reach inside this callback. No error is caught though.

**Comment by cognitiveplus** [comment] 2018-02-26 10:15
EDIT: Actually, there is a error - **unable to acquire camera stream**. Error logging was just broken in .catch branch.

**Comment by willeastcott** [comment] 2018-02-26 19:58
Hmm. Are you able to run any non-PlayCanvas apps on your device that use getUserMedia? For example:

https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by cognitiveplus** [comment] 2018-02-26 22:48
Nope, getting NotReadableError at this link. Seems like hardware / os issue with my device.

**Comment by willeastcott** [comment] 2018-02-26 23:45
Hmm. Seems so. Weird.

**Comment by Epikos1994** [comment] 2018-03-02 10:40
Hey Gents,

So I've been looking around and testing some things out. This looks like an issue for Chrome.

I tested the app using Samsung internet and I get the request to access camera and the app works fine.
(However it was using my front camera)

I'll keep digging some more and let you know what I find.

**Comment by willeastcott** [comment] 2018-03-02 15:25
If this is a Chrome bug (regression?), then you might want to report it on:

https://bugs.chromium.org/p/chromium/issues/list

They're normally quite responsive.

**Comment by cognitiveplus** [comment] 2018-03-02 18:10
It works in Firefox for me, so seems like Chrome issue indeed.

**Comment by Epikos1994** [comment] 2018-03-16 09:48
Hey Guys,

It's now working on Chrome. Believe this is Issue fixed?

Thanks,
Dean

**Comment by willeastcott** [comment] 2018-03-16 20:08
Thanks for the update. Closing...

**Closed as completed by willeastcott** 2018-03-16 20:08 UTC
